import "reflect-metadata";
import "./globals.css";

import type { Metadata } from "next";
import { QueryClientProvider } from "./providers/query-client-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<QueryClientProvider>{children}</QueryClientProvider>
			</body>
		</html>
	);
}
